### ISSUE TITLE
Says for tablet or laptop - does not work on Android tablet

### ISSUE THREAD

**Issue by coyoteconscious** [Mottokrosh/SheetIssues#12]
Actually, none of the links on the front page, including the "Launch App", email, or github issues links work at all on any browser on my Android tablet. The mailing list box seems to work, but nothing else.

Even long-press does nothing - does not bring up the contextual menu.

**Comment by Mottokrosh** [comment]
Hi Coyote,

That's a very strange issue since it's only a plain link with some CSS, but
you're the second person to report it so something is definitely wrong.
I'll look into it on Monday when I have access to an Android device.

In the meantime you can get to the app directly at:

http://charactersheet.co.uk/pathfinder

**Comment by coyoteconscious** [comment]
Yeah, it's kind of odd. I'm wondering whether it's something funny with 
the Mailchimp code. I've had it occasionally take over a page via 
z-index weirdness before on sites I've worked on.

I like what I see on the desktop side though!

Best wishes,

Coyote

**Comment by Mottokrosh** [comment]
Looks like it was the viewport slider plugin interfering with that link. I've removed that plugin, and the Launch button appears to be working correctly across the board now.

**Comment by coyoteconscious** [comment]
Excellent! I'll try it out today. Thanks for being so responsive, and sharing something so cool.
