### ISSUE TITLE
Unable To Archive Characters

### ISSUE THREAD

**Issue by GilesPenfold** [Mottokrosh/SheetIssues#20]
When clicking "Archive" on a character I get redirected to the login page and nothing happens in terms of the archiving. I am also unable to delete any archived characters.

**Comment by Mottokrosh** [comment]
Yep, looks like I introduced that in my recent deploy. Should have a fix soon.

**Comment by GilesPenfold** [comment]
Thanks! Do you know what happens to character sheets that are at the bottom of the list? As everytime I make a new character, the character at the bottom of the list disappears. I assume if I archive a character they'll move back up and I can access them again?

**Comment by Mottokrosh** [comment]
Fixed!

(I hope. :))

I had two very silly bugs that prevented character archiving and restoring, and both should be fixed now.

Additionally, there was a rather conservative limit to the number of characters you could display (not create) on the main page; 10 total between active and archived, which is why you saw characters seemingly disappearing from that list. That's now 50.

**Comment by GilesPenfold** [comment]
Great, thank you very much!

Our whole party is finding the app really useful, so thank you for making it!
